# -*- coding: utf-8 -*-
"""Slash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FGr5BXXE0k7jnXkCOfrj_pvuAOvyG1sS
"""

!pip install scrapy

!scrapy startproject slash

# Commented out IPython magic to ensure Python compatibility.
# %cd  slash/slash/spiders/

!scrapy genspider sl https://www.slashdigit.com/

# Commented out IPython magic to ensure Python compatibility.
# %%writefile sl.py
# import scrapy
# 
# 
# class SlSpider(scrapy.Spider):
#     name = "sl"
#     allowed_domains = ["www.slashdigit.com"]
#     start_urls = ["https://www.slashdigit.com/"]
# 
#     def parse(self, response):
#         posts=response.css('div.col-md-4.col-sm-12.col-xs-12.pt-cv-content-item.pt-cv-1-col')
#         print(len(posts))
#         for post in posts:
#             yield{
#               'title':post.css('div.pt-cv-ifield h2.pt-cv-title a::text').get()}

!scrapy crawl sl -o s_data.json

import json

with open('s_data.json','r') as file:
  data=json.load(file)

print(len(data))

first_post=data[0]
print(f"Title: {first_post['title']}")