# -*- coding: utf-8 -*-
"""Tunisianet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBHxbP2lRRqxSMLehuFBk6A-NniQnHMb
"""

!pip install scrapy

!scrapy startproject T

# Commented out IPython magic to ensure Python compatibility.
# %cd  T/T/spiders/

!scrapy genspider TN https://www.tunisianet.com.tn/300-informatique

# Commented out IPython magic to ensure Python compatibility.
# %%writefile TN.py
# import scrapy
# 
# class TnSpider(scrapy.Spider):
#     name = "TN"
#     allowed_domains = ["www.tunisianet.com.tn"]
#     start_urls = ["https://www.tunisianet.com.tn/300-informatique"]
# 
#     def parse(self, response):
#         posts=response.css('div.item-product.col-xs-12')
#         print(len(posts))
#         for post in posts:
#             yield{
#               'title':post.css('article.product-miniature.js-product-miniature.col-xs-12.propadding div.thumbnail-container.text-xs-center div.wb-product-desc.product-description.col-lg-5.col-xl-5.col-md-6.col-sm-6.col-xs-6 h2.h3.product-title a::text').get(),
#               'text':post.css('article.product-miniature.js-product-miniature.col-xs-12.propadding div.thumbnail-container.text-xs-center div.wb-product-desc.product-description.col-lg-5.col-xl-5.col-md-6.col-sm-6.col-xs-6 div.listds a p::text').get(),
#               'price':post.css('article.product-miniature.js-product-miniature.col-xs-12.propadding div.thumbnail-container.text-xs-center div.wb-product-desc.product-description.col-lg-5.col-xl-5.col-md-6.col-sm-6.col-xs-6 div.product-price-and-shipping span::text').get() }
#         page=response.css('nav.pagination div.col-md-6.cl-sm-6.col-xs-6.text-xs-right ul.page-list.clearfix li a.next.js-search-link').attrib['href']
#         if page :
#             yield response.follow(page,callback=self.parse)
# 
# 
# 
#

!scrapy crawl TN -o TN_data.json

import json

with open('TN_data.json','r') as file:
  data=json.load(file)

print(len(data))

npost=data[2640]
print(f"Title: {npost['title']}")
print(f"price: {npost['price']}")
print(f"Description: {npost['text']}")